<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('countries')->insert([
            ['country_name' => 'Afghanistan', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Albania', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Algeria', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Andorra', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Angola', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Antigua and Barbuda', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Argentina', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Armenia', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Australia', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Austria', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Azerbaijan', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'The Bahamas', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Bahrain', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Bangladesh', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Barbados', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Belarus', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Belgium', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Belize', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Benin', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Bhutan', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Bolivia', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Bosnia and Herzegovina', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Botswana', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Brazil', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Brunei', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Bulgaria', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Burkina Faso', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Burundi', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Cabo Verde', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Cambodia', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Cameroon', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Canada', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Central African Republic', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Chad', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Chile', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'China', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Colombia', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Comoros', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Congo, Democratic Republic of the', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Congo, Republic of the', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Costa Rica', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Côte d’Ivoire', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Croatia', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Cuba', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Cyprus', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Czech Republic', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Denmark', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Djibouti', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Dominica', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Dominican Republic', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'East Timor (Timor-Leste)', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Ecuador', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Egypt', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'El Salvador', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Equatorial Guinea', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Eritrea', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Estonia', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Eswatini', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Ethiopia', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Fiji', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Finland', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'France', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Gabon', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'The Gambia', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Georgia', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Germany', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Ghana', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Greece', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Grenada', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Guatemala', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Guinea', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Guinea-Bissau', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Guyana', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Haiti', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Honduras', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Hungary', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Iceland', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'India', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Indonesia', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Iran', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Iraq', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Ireland', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Israel', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Italy', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Jamaica', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Japan', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Jordan', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Kazakhstan', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Kenya', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Kiribati', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Korea, North', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Korea, South', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Kosovo', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Kuwait', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Kyrgyzstan', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Laos', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Latvia', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Lebanon', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Lesotho', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Liberia', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Libya', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Liechtenstein', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Lithuania', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Luxembourg', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Madagascar', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Malawi', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Malaysia', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Maldives', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Mali', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Malta', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Marshall Islands', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Mauritania', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Mauritius', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Mexico', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Micronesia, Federated States of', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Moldova', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Monaco', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Mongolia', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Montenegro', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Morocco', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Mozambique', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Myanmar (Burma)', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Namibia', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Nauru', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Nepal', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Netherlands', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'New Zealand', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Nicaragua', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Niger', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Nigeria', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'North Macedonia', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Norway', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Oman', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Pakistan', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Palau', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Panama', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Papua New Guinea', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Paraguay', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Peru', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Philippines', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Poland', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Portugal', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Qatar', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Romania', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Russia', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Rwanda', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Saint Kitts and Nevis', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Saint Lucia', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Saint Vincent and the Grenadines', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Samoa', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'San Marino', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Sao Tome and Principe', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Saudi Arabia', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Senegal', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Serbia', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Seychelles', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Sierra Leone', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Singapore', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Slovakia', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Slovenia', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Solomon Islands', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Somalia', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'South Africa', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Spain', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Sri Lanka', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Sudan', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Sudan, South', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Suriname', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Sweden', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Switzerland', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Syria', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Taiwan', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Tajikistan', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Tanzania', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Thailand', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Togo', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Tonga', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Trinidad and Tobago', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Tunisia', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Turkey', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Turkmenistan', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Tuvalu', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Uganda', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Ukraine', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'United Arab Emirates', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'United Kingdom', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'United States', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Uruguay', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Uzbekistan', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Vanuatu', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Vatican City', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Venezuela', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Vietnam', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Yemen', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Zambia', 'created_at' => now(), 'updated_at' => now()],
            ['country_name' => 'Zimbabwe', 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
